# Generated by Django 2.0.13 on 2019-04-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_remove_config_organization'),
        ('config', '0020_remove_config_context'),
    ]

    operations = [
    ]
