# Generated by Django 2.0.13 on 2019-04-04 07:07

import django.core.validators
from django.db import migrations, models
import jsonfield.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_remove_config_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='flag',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared_secret', 'Shared Secret'), ('external', 'Import')], db_index=True, default='private', help_text='Whether this template can be shared, remain private or will be imported', max_length=16, verbose_name='flag'),
        ),
        migrations.AddField(
            model_name='template',
            name='url',
            field=models.URLField(default='http://localhost', help_text='url of the template to be imported', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='template',
            name='variable',
            field=jsonfield.fields.JSONField(default=dict, help_text='Provide variable with sample values if present. Leave blank if variables are absent', verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='primary mac address', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'), code='invalid', message='Must be a valid mac address.')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
    ]
