# Generated by Django 2.0.13 on 2019-04-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_auto_20190408_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='template',
            name='variable',
        ),
    ]
