# Generated by Django 2.0.13 on 2019-04-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0035_auto_20190408_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatelibrary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='templatelibrary',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='templatelibrary',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='templatelibrary',
            name='vpn',
        ),
        migrations.DeleteModel(
            name='TemplateLibrary',
        ),
    ]
