# Generated by Django 2.0.13 on 2019-04-10 10:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_auto_20190409_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, help_text='Enter public description of this template', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='flag',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared_secret', 'Shared Secret'), ('public', 'Import')], db_index=True, default='private', help_text='Whether to keep this template private or make it public, shared secretly or imported', max_length=16, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='template',
            name='notes',
            field=models.TextField(blank=True, help_text='Enter internal notes for the administrators', null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='template',
            name='url',
            field=models.URLField(blank=True, help_text='Enter URL to import template from', null=True, verbose_name='Import From'),
        ),
        migrations.AddField(
            model_name='template',
            name='variable',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='Enter Values for the variables used by this template', verbose_name='Variable'),
        ),
    ]
