# Generated by Django 2.0.13 on 2019-04-10 19:21

import django.core.validators
from django.db import migrations, models
import django_netjsonconfig.utils
import re


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_auto_20190410_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='key',
            field=models.CharField(db_index=True, default=django_netjsonconfig.utils.get_random_key, help_text='unique template key', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[^\\s/\\.]+$'), code='invalid', message='Key must not contain spaces, dots or slashes.')]),
        ),
        migrations.AlterField(
            model_name='template',
            name='flag',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared_secret', 'Shared Secret'), ('import', 'Import')], db_index=True, default='private', help_text='Whether to keep this template private or make it public, shared secretly or imported', max_length=16, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='template',
            name='url',
            field=models.URLField(blank=True, help_text='Enter URL to import template from', null=True, verbose_name='URL'),
        ),
    ]
