# Generated by Django 2.0.13 on 2019-04-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_remove_config_organization'),
        ('config', '0038_auto_20190410_2121'),
    ]

    operations = [
    ]
