# Generated by Django 2.0.13 on 2019-04-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0007_default_groups_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='passphrase',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='passphrase',
        ),
    ]
